### ISSUE TITLE
ENOENT

### ISSUE THREAD

**Issue by dfcreative** [substack/tuner#10]
I use windows7, node 6.2 and get the following error:

```sh
npm i -g tuner

...

>tuner ksua
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn mplayer ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
```

**Comment by yoshuawuyts** [comment]
@dfcreative you need to have `mplayer` installed for this to work, do you have it on Windows?

**Comment by dfcreative** [comment]
Ah, I see. After installing mplayer it worked. Thanks.
